### ISSUE TITLE
[BUG]: 32 Bit support stopped working with 2.10

### ISSUE THREAD

**Issue by kwk** [wjakob/nanobind#1238]
### Problem description

Hi. We've been building Fedora packages of python-nanobind for a while and noticed with the recent update from 2.9 to 2.10 (both 2.10.0 and 2.10.1), that 32 bit support is no longer working.

We notice this when building mock packages for fedora-rawhide-i386 [here](https://kojipkgs.fedoraproject.org//work/tasks/6396/139836396/build.log):

```
  /builddir/build/BUILD/python-nanobind-2.10.1-build/nanobind-2.10.1/src/nb_internals.h:447:15: error: static assertion failed due to requirement 'pyobj_name::total_count * sizeof(_object *) == 96'
    447 | static_assert(pyobj_name::total_count * sizeof(PyObject*) == NB_MOD_STATE_SIZE);
        |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /builddir/build/BUILD/python-nanobind-2.10.1-build/nanobind-2.10.1/src/nb_internals.h:447:59: note: expression evaluates to '48 == 96'

```

The way I see it is this:
* You've modified `NB_MOD_STATE_SIZE` from `80` to `96`.
* You don't use `NB_MOD_STATE_SIZE` directly anywhere in the relevant patch.
* You've added two items to the `pyobj_name` int enum [here](https://github.com/wjakob/nanobind/commit/babec16ecdc8d49239d1b9e2991db85e2b5deac6#diff-8599263e788c107944d356ce118965942735cfbe16289ccf98ee5f8a33f0e808R431-R447).
* Then this assert which predates the patch fails:

```
static_assert(pyobj_name::total_count·*·sizeof(PyObject*)·==·NB_MOD_STATE_SIZE);
```

`48 != 96`

The addition of two items to the enum increases the total count also by two. Two pointers that is. Hence, on 32 bit it is 4*(10+2)=48 and on 64 bit that is 8*(10+2)=96, right? What's interesting is that this can never have worked on a 32 bit machine before (40 is never 80). Maybe over the course of changes from 2.9 to 2.10, this has been touched before. Let me see. Yes `NB_MOD_STATE_SIZE` was only introduced from 2.9.2 to 2.10.1 (see this [comparison](https://github.com/wjakob/nanobind/compare/v2.9.2...v2.10.1)).

Nanobind 2.9.2 was [buildable and tests did run](https://kojipkgs.fedoraproject.org//packages/python-nanobind/2.9.2/3.fc44/data/logs/i686/build.log) on 32 bit. Are you planning to support 32 bit in any way or is it explicitly unsupported?

### Reproducible example code

```text
$ git clone https://src.fedoraproject.org/forks/kkleine/rpms/python-nanobind.git
$ cd python-nanobind
$ git reset --hard origin/release-2.10.1
$ make mockbuild MOCK_CHROOT=fedora-rawhide-i386
```
