### ISSUE TITLE
[BUG]: Compilation for macOS <10.14

### ISSUE THREAD

**Issue by laggykiller** [wjakob/nanobind#433]
### Problem description

Currently nanobind compiles with macOS deployment target of >=10.14 (MACOSX_DEPLOYMENT_TARGET). It is usual for wheels of python to have target of 10.9, probably due to it being [the minimum version that python support](https://www.python.org/downloads/release/python-3118/).

Seems like the only line that cause compilation to fail on <10.14 is https://github.com/wjakob/nanobind/blob/e9aa496c3c9b560d675d06cb6a1c9262cb2230fe/src/nb_type.cpp#L231

```
nanobind/src/nb_type.cpp:231:13: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer
              operator delete(p, std::align_val_t(t->align));
              ^
nanobind/src/nb_type.cpp:231:13: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
```

(https://github.com/laggykiller/apngasm-python/actions/runs/8085333979/job/22092630596#step:4:858)

As a workaround, I add `-fno-aligned-allocation` to `CMAKE_CXX_FLAGS` and it compiles successfully.

I am not familiar with C++, would it be easy to rewrite this line so that it is compatible with macOS 10.9?

If it is not easy to rewrite, then let's just leave it be. In such case, may I ask what could go wrong if I add `-fno-aligned-allocation`? Adding that feels like a bad idea. If it is not too bad of an idea, should we update documentation about this workaround?

Edit: Seems like nanobind requires C++17 compiler according to main page of nanobind documentation, and first support for C++17 is [Xcode 10](https://developer.apple.com/documentation/xcode-release-notes/xcode-10-release-notes) (SDK for macOS 10.14). Given that only one line has to be changed (?), would you consider supporting macOS 10.9?

**Comment by wjakob** [comment]
macos 10.9 as in macOS mavericks. That was a long time ago!

This is unrealistic since this OS is missing core C++17 features that nanobind depends on. Please set a minimum deployment target, as shown in the example project: https://github.com/wjakob/nanobind_example/blob/master/pyproject.toml#L43
